import type { CommunityConfig, CommunityRole, CreateCommunityInput } from '@/types/community';
import { TEMPLATE_LABELS, ALL_PERMISSIONS } from '@/types/community';

export function createDefaultCommunityConfig(input: CreateCommunityInput, ownerId: string): CommunityConfig {
  const createdAt = Date.now();
  const templateLabel = TEMPLATE_LABELS[input.template];
  const publicServer = input.visibility === 'public';

  const roles: CommunityRole[] = [
    {
      id: 'owner',
      name: 'Owner',
      description: 'Full community control',
      color: '#f59e0b',
      icon: 'crown',
      position: 100,
      permissions: ALL_PERMISSIONS,
      mentionable: false,
      hoisted: true,
    },
    {
      id: 'admin',
      name: 'Admin',
      description: 'Manage server settings, roles, channels, bots, and automations',
      color: '#ef4444',
      icon: 'shield',
      position: 80,
      permissions: ALL_PERMISSIONS.filter(p => p !== 'export_data' && p !== 'manage_monetization'),
      mentionable: false,
      hoisted: true,
    },
    {
      id: 'moderator',
      name: 'Moderator',
      description: 'Moderate conversations and keep the community safe',
      color: '#3b82f6',
      icon: 'gavel',
      position: 60,
      permissions: [
        'view_channels',
        'send_messages',
        'manage_messages',
        'kick_members',
        'ban_members',
        'timeout_members',
        'mute_members',
        'manage_moderation',
        'view_audit_log',
        'create_threads',
        'manage_threads',
      ],
      mentionable: true,
      hoisted: true,
    },
    {
      id: 'member',
      name: 'Member',
      description: 'Verified community member',
      color: '#22c55e',
      position: 20,
      permissions: [
        'view_channels',
        'send_messages',
        'stream',
        'create_threads',
        'create_polls',
        'create_invites',
        'use_ai',
      ],
      mentionable: true,
      hoisted: false,
    },
    {
      id: 'newcomer',
      name: 'Newcomer',
      description: 'Limited access until onboarding or trust checks complete',
      color: '#94a3b8',
      position: 10,
      permissions: ['view_channels', 'send_messages'],
      mentionable: false,
      hoisted: false,
      temporary: true,
    },
  ];

  return {
    version: 1,
    template: input.template,
    branding: {
      description: input.description || `${templateLabel} community on Local Echo`,
      icon: input.icon,
      bannerUrl: input.bannerUrl,
      accentColor: '#22c55e',
      gradientFrom: '#0f172a',
      gradientTo: '#14532d',
      welcomeTitle: `Welcome to ${input.name}`,
      welcomeMessage: input.aiSetupEnabled
        ? `This ${templateLabel.toLowerCase()} space was set up with recommended channels, roles, safety defaults, and onboarding.`
        : 'Read the rules, introduce yourself, and make yourself at home.',
      inviteSplash: `Join ${input.name} on Local Echo.`,
    },
    discovery: {
      visibility: input.visibility,
      tags: input.tags,
      language: input.language,
      region: input.region,
      allowDiscovery: input.visibility === 'public',
    },
    invites: {
      defaultExpiryHours: publicServer ? 24 : 168,
      maxUses: publicServer ? 100 : 25,
      allowMemberInvites: !publicServer,
      requireApproval: publicServer,
      trackAnalytics: true,
    },
    onboarding: {
      enabled: input.onboardingTemplate !== 'none',
      template: input.onboardingTemplate,
      rules: [
        'Be respectful and constructive.',
        'No spam, scams, harassment, or hate speech.',
        'Keep discussions in the right channels.',
      ],
      starterPrompt: 'Introduce yourself and tell everyone what brought you here.',
      assignRoleOnComplete: 'member',
    },
    roles,
    permissionOverwrites: [],
    moderation: {
      verificationLevel: publicServer ? 'medium' : 'low',
      spamDetection: true,
      raidDetection: publicServer,
      scamDetection: true,
      phishingDetection: true,
      nsfwDetection: publicServer,
      hateSpeechFilter: true,
      toxicityScoring: publicServer,
      duplicateMessageDetection: true,
      antiMassMention: true,
      quarantineNewMembers: publicServer,
      trustScoreEnabled: true,
      emergencyLockdown: false,
      panicMode: false,
    },
    automodRules: [
      { id: 'spam-rule', name: 'Spam shield', enabled: true, trigger: 'spam', threshold: 5, action: 'timeout' },
      { id: 'mentions-rule', name: 'Mass mention guard', enabled: true, trigger: 'mass-mention', threshold: 6, action: 'delete-message' },
      { id: 'scam-rule', name: 'Suspicious link review', enabled: true, trigger: 'link', threshold: 1, action: 'notify-mods' },
    ],
    automations: [
      {
        id: 'welcome-flow',
        name: 'Welcome new members',
        enabled: true,
        trigger: 'member-joins',
        condition: 'Always',
        action: 'send-message',
        description: 'Posts a welcome message and points newcomers to onboarding.',
      },
      {
        id: 'trusted-role-flow',
        name: 'Unlock trusted member role',
        enabled: input.aiSetupEnabled,
        trigger: 'level-reached',
        condition: 'Level >= 10 and no active strikes',
        action: 'assign-role',
        description: 'Promotes healthy long-term members into a trusted role.',
      },
    ],
    analytics: {
      enabled: true,
      retentionDays: publicServer ? 90 : 30,
      trackMessageActivity: true,
      trackVoiceActivity: true,
      trackModerationStats: true,
      aiInsights: input.aiSetupEnabled,
    },
    integrations: {
      botsEnabled: true,
      pluginsEnabled: true,
      webhooksEnabled: true,
      githubEnabled: input.template === 'developer' || input.template === 'startup',
      pluginSandboxRequired: true,
      marketplaceEnabled: input.visibility === 'public',
    },
    monetization: {
      enabled: false,
      premiumMemberships: false,
      paidRoles: false,
      donations: input.template === 'creator-community',
      ticketedChannels: false,
      supporterBadges: input.template === 'creator-community',
    },
    backups: {
      enabled: false,
      encrypted: true,
      retentionDays: 30,
      includeAuditLogs: true,
    },
    auditLog: [
      {
        id: `audit-${createdAt}`,
        actorId: ownerId,
        action: 'community.created',
        target: input.name,
        reason: `Created from ${templateLabel} template`,
        timestamp: createdAt,
      },
    ],
  };
}
